---
book_repo: pivotal-cf/docs-book-compliance-tools
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master
feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
- repository:
    name: pivotal-cf/docs-addon-compliance-tools
    ref: 'v1.0.0-beta.7'
  directory: addon-compliance-tools/1-0
  subnav_template: addon_compliance_tools_1_0.erb
  product_info:
    use_local_header: true
    latest_stable_version: '1.0'
    local_header_img: /images/cloud_rings.png
    local_header_title: Compliance Scanner for PCF
    search_placeholder: Search Compliance Scanner v1.0
    url_prefix: addon-compliance-tools/1-0
    local_product_version: 1.0
    local_header_links: []
    local_header_version_list:
