---
book_repo: pivotal-cf/docs-book-compliance-tools
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

- repository:
    name: pivotal-cf/docs-addon-compliance-tools
    ref: 'master'
  directory: addon-compliance-tools/1-0
  subnav_template: addon_compliance_tools_1-0.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.0
    local_header_img: /images/cloud_rings.png
    local_header_title: Caliper Add-On for PCF
    search_placeholder: Search Caliper Add-On 1.0
    url_prefix: addon-compliance-tools/1-0
    local_product_version: 1.0